-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'LISTING_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'ESCROW_PAID';
ALTER TYPE "NotificationType" ADD VALUE 'ESCROW_RELEASED';
ALTER TYPE "NotificationType" ADD VALUE 'ESCROW_REFUNDED';
ALTER TYPE "NotificationType" ADD VALUE 'TRANSFER_DOWNGRADE_PROPOSAL';
ALTER TYPE "NotificationType" ADD VALUE 'ESCROW_DISPUTE_OPENED';
ALTER TYPE "NotificationType" ADD VALUE 'ESCROW_DISPUTE_RESOLVED';
ALTER TYPE "NotificationType" ADD VALUE 'REVIEW_REQUESTED';
